### ISSUE TITLE
pronto-reek doesn't respect --exit-code option

### ISSUE THREAD

**Issue by edude03** [prontolabs/pronto-reek#15]
I'm experimenting with using reek as part of our CI process however I'm noticing that reek seems to always return 0 (success) even though it logs a number of issues.

Is this the expected behaviour, and if so, can it be overridden?

**Comment by mmozuras** [comment]
@edude03 could it be because of https://github.com/mmozuras/pronto-reek/pull/13?

**Comment by dstull** [comment]
ugh..seems like it- can we make this configurable?

**Comment by mmozuras** [comment]
@dstull sure, go ahead, I'd be open to a PR implementing it 😄

**Comment by dstull** [comment]
hmm, I was just looking into doing that...but I'm more of the opinion that https://github.com/prontolabs/pronto-reek/pull/13 should be reverted.  The whole point of using this is to be made aware of possible issues, if ran manually and automatically.  If someone wants to mute a reek smell, then they should exclude it in their .reek file or inline...not here.

**Comment by ashkulz** [comment]
@dstull is this still an issue?

**Comment by dstull** [comment]
@ashkulz i have since changed jobs, and no longer use it.  So not for me, but maybe for others if they use this.

**Comment by Drowze** [comment]
Hey guys, I bumped into this issue today! I'm using pronto (with pronto-reek) along with git-hooks managed by [Overcommit](https://github.com/sds/overcommit). Overcommit is unfortunately swallowing errors coming from pronto-reek since it does not return an error code 😢 (see https://github.com/sds/overcommit/issues/754)
