### ISSUE TITLE
Pronto-reek comments on files that are in exclude_paths

### ISSUE THREAD

**Issue by ibrahima** [prontolabs/pronto-reek#19]
Currently, pronto-reek will still check and comment on files that are in `exclude_paths` in your reek configuration. It seems like pronto-reek should be somehow setting the force_exclusion option to true as introduced in https://github.com/troessner/reek/pull/1200 .

I'll introduce a PR if I have time!

**Comment by ibrahima** [comment]
Actually, I'm not totally sure if there's a way for API consumers to set that option, it seems like a CLI only option right now. But I guess we can always add a dummy CLI options object just to pass that option.

**Comment by mvz** [comment]
Yes, it only influences how the CLI converts the paths given on the command line into a set of file paths to process. The Examiner object does not look at exclusions at all.

Your best bet for now is probably to check the current file against `configuration.excluded_paths` yourself.

**Comment by ibrahima** [comment]
Good point, we can definitely do that within pronto-reek.

**Comment by timseal** [comment]
I got round this by adding the excluded directories in the `.pronto.yml` file:
```yml
reek:
  exclude:
    - 'db/**/*'
```
